version: "3"

services:
  mawaqit-api:
    image: mrsofiane/mawaqit-api:latest
    ports:
      - "80:80"
    depends_on:
      - mawaqit-api-redis
    environment:
      - REDIS_URI=redis://mawaqit-api-redis:6379
      - USE_REDIS=true

  mawaqit-api-redis:
    image: redis:alpine3.18
    ports:
      - "6379:6379"
